---
blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: >-
      https://github.com/Akiffazal/Pea-Plant-Disease-Classification/discussions
    about: Please use GitHub Discussions for questions and general discussions
